### ISSUE TITLE
For Amorphous or liquid systems

### ISSUE THREAD

**Issue by Tingliangstu** [tyst3273/pynamic-structure-factor#1]
Hi, Sterling, the pynamic is suitable for calculating the structure factor of amorphous or liquid systems?

**Comment by tyst3273** [comment]
Yes, in principle it is. I used it for hybrid perovskite which is
disordered.

Still, you have to be careful how you choose your Q point grid. Please look
at the manual for explanation. Note that in experiments what is measured
for liquids etc is spherically averaged, so its actually S(|Q|,w) that's
measured. My code doesn't spherically average, it calculated on a grid. You
could average after the fact if you wanted.

If you have any trouble, please let me know! I havent used it for liquid or
amorphous systems before so would be interested in seeing how it works.

Thanks!
Ty

**Comment by tyst3273** [comment]
since this isn't an issue with the code but just a question about it, i will close it. thanks!

**Comment by Tingliangstu** [comment]
Well noted. Thanks so much, Ty.
